name: Build SunamoTextOutputGenerator

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoTextOutputGenerator
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoTextOutputGenerator/SunamoTextOutputGenerator.csproj

    - name: Build
      run: dotnet build SunamoTextOutputGenerator/SunamoTextOutputGenerator.csproj --configuration Release --no-restore

  test:
    name: Test SunamoTextOutputGenerator.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoTextOutputGenerator.Tests/SunamoTextOutputGenerator.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoTextOutputGenerator.Tests/SunamoTextOutputGenerator.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoTextOutputGenerator.Tests/SunamoTextOutputGenerator.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
